### ISSUE TITLE
Selecting an entry from cmp_nvim_r adds an extra intitial character

### ISSUE THREAD

**Issue by fbearoff** [jalvesaq/cmp-nvim-r#1]
If you select an entry for the cmp_nvim_r source using [Enter] it adds an extra initial character to the completion

 i.e.  dataframe -->**d**dataframe

**Comment by jalvesaq** [comment]
Thanks for reporting the issue. I can replicate it, but only if I select the entry with `<Enter>`.  If I press the space bar or insert an opening parenthesis, there is no problem.

**Comment by jalvesaq** [comment]
It should be fixed now.
