### ISSUE TITLE
Autocomplete trigger on  new line following the `+` or `|>` operators

### ISSUE THREAD

**Issue by PMassicotte** [jalvesaq/cmp-nvim-r#10]
I've observed an issue with the autocomplete functionality that requires me to manually trigger it using ctrl-space when I move to a new line that ends with either a `+` or `|>`.

![Peek 2023-10-26 07-47](https://github.com/jalvesaq/cmp-nvim-r/assets/4519221/1d082c5e-2287-4b3d-a915-35ac874f082b)

Any idea to trigger the autocomplete on a new line automatically as I type?

**Comment by jalvesaq** [comment]
This bug was introduced by https://github.com/jalvesaq/cmp-nvim-r/commit/4deaee45c9b10b03c0ee02f1924a4550dd921594 and maybe it would be fixed if the completion was reset at this point: https://github.com/jalvesaq/cmp-nvim-r/blob/58b5ecd4f7babe0bbf5f7e73a1a51b3daf309bd8/lua/cmp_nvim_r/init.lua#L638

**Comment by PMassicotte** [comment]
Thank you !
