### ISSUE TITLE
Autocomplete is only showing one suggestion

### ISSUE THREAD

**Issue by PMassicotte** [jalvesaq/cmp-nvim-r#11]
I have noticed that since one of the last update (not sure if nvim-r or cmp-nvim-r), I am not getting all columns from the data frame (only 1 item/column is showing)

![image](https://github.com/jalvesaq/cmp-nvim-r/assets/4519221/e352fbd3-c04f-4105-b2ba-451bbd5414e8)
![image](https://github.com/jalvesaq/cmp-nvim-r/assets/4519221/e7e3dce7-02e7-4321-9f88-793afaf9cc76)
![image](https://github.com/jalvesaq/cmp-nvim-r/assets/4519221/dab8b257-fc3c-48b7-8dec-54d8cf9fab3d)

**Comment by jalvesaq** [comment]
Thanks for reporting the bug. It should be fixed on Nvim-R.

**Comment by PMassicotte** [comment]
Thank you very much for your work. Much appreciated. I will let you close this issue :)
