### ISSUE TITLE
Function signature arguments not showing!

### ISSUE THREAD

**Issue by drusmanbashir** [jalvesaq/cmp-nvim-r#12]
Hi I have recently started using R with neovim. This plugin is so great, i dont use RStudio anymore!

I have noticed an issue: Whenever I enter the parenthesis of a function I am typing (e.g., print()), an error appears in the r console. Below is a clip:

[Screencast from 03-02-24 23:26:09.webm](https://github.com/jalvesaq/cmp-nvim-r/assets/5282314/909d7666-5fb5-46f4-b6f3-c64d3c2eca64)

My cmp_nvim_r config file is:

```
require'cmp_nvim_r'.setup({
  filetypes = {'r', 'rmd', 'quarto'},
  doc_width = 58
  })
vim.cmd[[
set nosplitright

let R_rconsole_width = winwidth(0) / 2
let R_assign= 0
let nosplitright = 1
let R_objbr_place = 'console,below'
let R_objbr_h = 25
let R_objbr_auto_start =0
let R_auto_start=2
autocmd VimResized * let R_rconsole_width = winwidth(0) / 2
function! s:customNvimRMappings()

   nmap <buffer> <M-e> <leader>d
   " imap <buffer> <M-e> <Esc><leader>d


   imap <buffer> <M--> <-
   imap <buffer> <M-,> %>% 
   vmap <buffer> <M-e> <leader>sd
   " nmap <buffer> <M-x> <leader>mij/^# %%<CR><CR>
   nmap <buffer> <M-x> l[hv]h<leader>sd
endfunction
augroup myNvimR
   au!
   autocmd filetype r call s:customNvimRMappings()
augroup end
]]

```

My nvim-cmp file has the following sources section

```
 sources = cmp.config.sources({
    { name = "nvim_lsp",  keyword_length = 3 },
    { name = "cmp_nvim_r" },
    { name = "luasnip" }, -- For luasnip users.
    { name = "codeium" },
  }, {
    { name = "buffer" },
    { name = "path" },
  }),
  completion = {
    keyword_length = 1, -- default
  },
  confirm_opts = {
    behavior = cmp.ConfirmBehavior.Replace,
    select = false,
  },
```

**Comment by jalvesaq** [comment]
This was supposed to have been fixed by https://github.com/jalvesaq/Nvim-R/pull/800
Are all your plugins up to date?

**Comment by drusmanbashir** [comment]
Yes every plugin up to date. I have also put

```
options(languageserver.server_capabilities =
        list(completionProvider = FALSE, completionItemResolve = FALSE))
```
in my .Rprofile just in case.

**Comment by jalvesaq** [comment]
The current version of `nvimcom` is `0.9-162`. That's what you should see with `:RDebugInfo`...

Note: `grep -R sdq` returns nothing in either `Nvim-R` or `cmp-nvim-r` directory. So, it's impossible that the bug is caused by the **current** versions of these plugins.

**Comment by drusmanbashir** [comment]
![image](https://github.com/jalvesaq/cmp-nvim-r/assets/5282314/0d195755-cab1-4b6d-b42d-af6f50a5a86a)

Yup same version.
I am wondering if there may be a clashing plugin installed?
I did install the r languageserver a few days ago, just before i started using R after a long time. But upon reading previous threads I uninstalled it using r remove.packages, and also Mason within neovim.

**Comment by jalvesaq** [comment]
I will increase nvimcom version number to force its recompilation. I think this is the cause of the problem.

**Comment by jalvesaq** [comment]
Could you try again, please?

**Comment by drusmanbashir** [comment]
Yes, that solved the problem. Thank you sir!

A side-question: Is it possible to integrate your plugin with [lsp-signature,](https://github.com/ray-x/lsp_signature.nvim) so that once inside the function parenthesis, function signature pops up.

**Comment by jalvesaq** [comment]
Anything specific to Neovim will be easier when "tmp-R-Nvim" becomes "R-Nvim". Please, see https://github.com/jalvesaq/Nvim-R/discussions
