### ISSUE TITLE
Doesit work with R.nvim?

### ISSUE THREAD

**Issue by raffaelemancuso** [jalvesaq/cmp-nvim-r#13]
README says:

> Completion source for [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) using [Nvim-R](https://github.com/jalvesaq/Nvim-R) as backend.

Does it work R.nvim?

Is one of the two compulsory?

What if I don't install neither of them?

What if I install both of them?

**Comment by jalvesaq** [comment]
Em seg., 4 de mar. de 2024 13:12, Raffaele Mancuso ***@***.***>
escreveu:

> README says:
>
> Completion source for nvim-cmp <https://github.com/hrsh7th/nvim-cmp>
> using Nvim-R <https://github.com/jalvesaq/Nvim-R> as backend.
>
> Does it work R.nvim?
>

No.

Is one of the two compulsory?
>

No.

What if I don't install neither of them?
>

You don't get auto completion.

What if I install both of them?
>

You have to configure only one.

**Comment by raffaelemancuso** [comment]
I realized  that with neovim you are supposed to use https://github.com/R-nvim/cmp-r together with https://github.com/R-nvim/R.nvim.

But then I don't understand why is this called cmp-**nvim**-r :)

**Comment by jalvesaq** [comment]
One is "cmp-nvim-r" and the other is "cmp-r". `R.nvim` code was optimized for Lua and auto-completion with `nvim-cmp` + `cmp-r`, while `Nvim-R` is optimized for VimScript and the legacy omni-completion (`<C-X<<C-O>`).

**Comment by raffaelemancuso** [comment]
Yes understood.

Thanks.
